### ISSUE TITLE
updateNifti only working for certain attributes

### ISSUE THREAD

**Issue by mathesong** [jonclayden/RNifti#9] opened 2018-02-20 15:10 UTC
Hi!  May I first just say that this package is brilliant, and that i love its speed, and I'm so happy that it exists.

I ran into an issue today with trying to rescale nii images, in that some attributes seem to be possible to update, while others were not.

## Load some data
```r
library(RNifti)
#> Warning: package 'RNifti' was built under R version 3.4.3

devtools::install_github('muschellij2/kirby21.t1')
#> Using GitHub PAT from envvar GITHUB_PAT
#> Skipping install of 'kirby21.t1' from a github remote, the SHA1 (01795b50) has not changed since last install.
#>   Use `force = TRUE` to force installation

kirby21.t1::download_t1_data()
#> [1] TRUE

kirby21.t1::get_t1_filenames()
...
```

## Original file attributes

```r
dat <- RNifti::readNifti(kirby21.t1::get_t1_filenames()[1])
dumpNifti(dat)
#> NIfTI-1 header
#>     sizeof_hdr: 348
#>       dim_info: 0
#>            dim: 3  170  256  256  1  1  1  1
#>      intent_p1: 0
#>      intent_p2: 0
#>      intent_p3: 0
#>    intent_code: 0  # HERE
#>       datatype: 64
#>         bitpix: 64
#>    slice_start: 0
#>         pixdim: -1.0  1.2  1.0  1.0  0.0  0.0  0.0  0.0
#>     vox_offset: 352
#>      scl_slope: 0  # HERE
#>      scl_inter: 0
#>      slice_end: 0
#>     slice_code: 0
#>     xyzt_units: 10
#>        cal_max: 2408322  # HERE
#>        cal_min: 0
#> slice_duration: 0
#>        toffset: 0
#>        descrip: Magnetic Resonance
#>       aux_file:  
#>     qform_code: 1
#>     sform_code: 0
#>      quatern_b: 1
#>      quatern_c: 0
#>      quatern_d: 0
#>      qoffset_x: -202.8
#>      qoffset_y: 0
#>      qoffset_z: 0
#>         srow_x: 0  0  0  0
#>         srow_y: 0  0  0  0
#>         srow_z: 0  0  0  0
#>    intent_name:  
#>          magic: n+1
```

## Updating intent_code works fine

```r
dat2 <- RNifti::updateNifti(dat, list(intent_code=1))
dumpNifti(dat2)
#> NIfTI-1 header
#>     sizeof_hdr: 348
#>       dim_info: 0
#>            dim: 3  170  256  256  1  1  1  1
#>      intent_p1: 0
#>      intent_p2: 0
#>      intent_p3: 0
#>    intent_code: 1  # HERE
#>       datatype: 64
#>         bitpix: 64
#>    slice_start: 0
#>         pixdim: 0.0  1.2  1.0  1.0  0.0  0.0  0.0  0.0
#>     vox_offset: 348
#>      scl_slope: 0
#>      scl_inter: 0
#>      slice_end: 0
#>     slice_code: 0
#>     xyzt_units: 10
#>        cal_max: 2408322
#>        cal_min: 0
#> slice_duration: 0
#>        toffset: 0
#>        descrip: 
#>       aux_file: 
#>     qform_code: 0
#>     sform_code: 0
#>      quatern_b: 0
#>      quatern_c: 0
#>      quatern_d: 0
#>      qoffset_x: 0
#>      qoffset_y: 0
#>      qoffset_z: 0
#>         srow_x: 0  0  0  0
#>         srow_y: 0  0  0  0
#>         srow_z: 0  0  0  0
#>    intent_name: 
#>          magic: n+1
```

## Updating scl_slope or cal_max does not work

```r
dat3 <- RNifti::updateNifti(dat, list(scl_slope=5))
dumpNifti(dat3)
#> NIfTI-1 header
#>     sizeof_hdr: 348
#>       dim_info: 0
#>            dim: 3  170  256  256  1  1  1  1
#>      intent_p1: 0
#>      intent_p2: 0
#>      intent_p3: 0
#>    intent_code: 0
#>       datatype: 64
#>         bitpix: 64
#>    slice_start: 0
#>         pixdim: 0.0  1.2  1.0  1.0  0.0  0.0  0.0  0.0
#>     vox_offset: 348
#>      scl_slope: 0  # HERE
#>      scl_inter: 0
#>      slice_end: 0
#>     slice_code: 0
#>     xyzt_units: 10
#>        cal_max: 2408322
#>        cal_min: 0
#> slice_duration: 0
#>        toffset: 0
#>        descrip: 
#>       aux_file: 
#>     qform_code: 0
#>     sform_code: 0
#>      quatern_b: 0
#>      quatern_c: 0
#>      quatern_d: 0
#>      qoffset_x: 0
#>      qoffset_y: 0
#>      qoffset_z: 0
#>         srow_x: 0  0  0  0
#>         srow_y: 0  0  0  0
#>         srow_z: 0  0  0  0
#>    intent_name: 
#>          magic: n+1


dat4 <- RNifti::updateNifti(dat, list(cal_max=1000))
dumpNifti(dat4)
#> NIfTI-1 header
#>     sizeof_hdr: 348
#>       dim_info: 0
#>            dim: 3  170  256  256  1  1  1  1
#>      intent_p1: 0
#>      intent_p2: 0
#>      intent_p3: 0
#>    intent_code: 0
#>       datatype: 64
#>         bitpix: 64
#>    slice_start: 0
#>         pixdim: 0.0  1.2  1.0  1.0  0.0  0.0  0.0  0.0
#>     vox_offset: 348
#>      scl_slope: 0
#>      scl_inter: 0
#>      slice_end: 0
#>     slice_code: 0
#>     xyzt_units: 10
#>        cal_max: 2408322  # HERE
#>        cal_min: 0
#> slice_duration: 0
#>        toffset: 0
#>        descrip: 
#>       aux_file: 
#>     qform_code: 0
#>     sform_code: 0
#>      quatern_b: 0
#>      quatern_c: 0
#>      quatern_d: 0
#>      qoffset_x: 0
#>      qoffset_y: 0
#>      qoffset_z: 0
#>         srow_x: 0  0  0  0
#>         srow_y: 0  0  0  0
#>         srow_z: 0  0  0  0
#>    intent_name: 
#>          magic: n+1
```

Any idea why this might be the case?  I'm looking to implement a system to change the units of a PET image in nii format, and there are different units which involve a scalar multiplicative change.  But neither way that I would do this appears to work.

Thanks again for this tool: it's a really awesome package!

All the best,
Granville

**Comment by jonclayden** [comment] 2018-02-20 15:46
Hi Granville! I'm glad you find the package helpful.

With regard to `cal_max` and `cal_min`, you should find that the current development version of the package (i.e. the tip of the `master` branch) should not reset them in these cases. The code has indeed been a bit over-aggressive there in the past—partly because some other packages expected `cal_max` to match the maximum pixel value in the image—but I think it can be relaxed now.

With `scl_slope` and `scl_inter` the issue is more complex. `RNifti` tries to give you flexibility while still benefitting from the speed of the C/C++ code, but it is important for it to ensure that the internal C structure and the R array are in sync whenever they interface with each other. Since the slope and intercept affect the numerical interpretation of the pixel values, and they have no analogue in R that is stable across arbitrary numerical operations, it is hard to guarantee that everything is in sync in every case. It is simply much safer to fix them to zero when there is both a R and a C object in play.

Admittedly this could be better documented, though, and I will try and fix that before the next release.

**Comment by jonclayden** [comment] 2018-03-22 15:52
This is now documented. If you need to set the scale and slope, for example to reduce file size, the natural time for that may be at the time of writing to file. If that's something you need, let me know and I'll look into adding it to `writeNifti`.

In the meantime I'll close this issue, since `cal_max` and `cal_min` can now be set, and the fact that `scl_slope` and `scl_inter` can't is now documented.

**Closed by jonclayden** 2018-03-22 15:52 UTC
